

# get tokens
# loop over tokens and color by TokenType
# indications of nullability, triggers, checks and no-access comes later and elsewhere.
# autocompletion is later and elsewhere.
# embddedment is also later and elsewhere.
# hinting autogenerated text is in another file. it can also be toggled on/off in settings

# ----------- colors -------------
# keywords, identifiers, parameter (e.g. var), literals, strings, comments, types, 
# comma, brackets, operators, functions, errors, default for unrecognized
# evt. give separate colors to schema, tree, table, column, view, aliases
# 

# ----------- ChatGPT suggests ----------- #
# Bad Token: #FF0000 (bright red) – typically indicates errors or invalid tokens.
# Braces: #A9B7C6 (light gray-blue) – for {} characters.
# Brackets: #A9B7C6 (light gray-blue) – for [] characters.
# Column: #9876AA (light purple) – for database column names.
# Comma: #A9B7C6 (light gray-blue) – for commas , in code.
# Comment: #808080 or #629755 (grayish-green) – for comments in SQL or other code.
# Database Object: #CC7832 (orange) – for database objects such as tables, views, etc.
# Dot: #A9B7C6 (light gray-blue) – for dots . in expressions.
# External Command: #9876AA (light purple) – for external references or commands.
# Keyword: #CC7832 (orange) – for SQL keywords like SELECT, FROM, WHERE.
# Label: #E8BF6A (light yellow) – for labels used in procedures or loops.
# Number Token: #6897BB (light blue) – for numeric literals like 123, 1.23.
# Outer Query Column: #9876AA (light purple) – for columns used in outer queries.
# Parameter: #9876AA (light purple) – for SQL parameters (e.g., in prepared statements).
# Parenthesis: #A9B7C6 (light gray-blue) – for () characters.
# Procedure or Function: #FFC66D (light orange) – for procedure or function names.
# Schema: #9876AA (light purple) – for schema names in fully qualified names.
# Semicolon: #A9B7C6 (light gray-blue) – for semicolons ; in SQL or other code.
# String Token: #6A8759 (green) – for string literals like 'text', "text".
# Synthetic Entity: #A9B7C6 (light gray-blue) – for system-generated entities.
# Table: #FFC66D (light orange) – for table names in SQL queries.
# Table or Columns Alias: #9876AA (light purple) – for aliases in SQL queries.
# Type: #CC7832 (orange) – for SQL types like VARCHAR, INT, DATE.
# Variable: #9876AA (light purple) – for variables in SQL procedures or scripts.

