
import operator
from functools import reduce
from enum import IntFlag, auto
from lsprotocol import types as t
from tools.server import server, serverType
# from sapi._internals.tokenizer
from tools import data_model
from sqlglot import TokenType # temp
from sqlglot.tokens import _ALL_TOKEN_TYPES # temp
import sapi
from sapi._internals.token_tree import TokenTree # temp
from dataclasses import dataclass, field
from tools.log import log
token_type_names = [name for name, type in TokenType.__members__.items()] # temp
if 'TOKEN_TREE' not in token_type_names:
    token_type_names.append('TOKEN_TREE')
    log("adding TOKEN_TREE")
log("TOKEN_TREE" in token_type_names)
# log(token_type_names)
# log(_ALL_TOKEN_TYPES)


class TokenModifier(IntFlag):
    # deprecated = auto()
    # readonly = auto()
    # defaultLibrary = auto()
    definition = auto()
modifier_names = [m.name for m in TokenModifier]
# get TokenTypes as list[str] from sapi parser
# also contruct modifier information in parser e.g. via optional out flag


@dataclass
class Token:
    line: int
    offset: int
    text: str
    tok_type: str #= ""
    tok_modifiers: list[TokenModifier] # = field(default_factory=list)


@server.feature(
    t.TEXT_DOCUMENT_SEMANTIC_TOKENS_FULL,
    t.SemanticTokensLegend(token_types=token_type_names, token_modifiers=modifier_names)
    )
def semantic_tokens_full(_: serverType, params: t.SemanticTokensParams) -> t.SemanticTokens:
    """Return the semantic tokens for the entire document"""
    # repeated code
    document_uri = params.text_document.uri
    if not document_uri.endswith('.sapi'):
        return []
    document = server.workspace.get_text_document(document_uri)
    # repeated code
    fal_dataModel = data_model.make_datamodel()
    if fal_dataModel.is_err():
        server.show_message(fal_dataModel.err, t.MessageType.Error)
        return []
    
    sapi_query = '\n'.join([line.strip('\n\r') for line in document.lines]) # assumes the document only contains one query
    tok_trees = sapi.parse(sapi_query, fal_dataModel.ok, list[TokenTree]) # try-parse

    ## get tokens from tok_trees
    tokens: list[Token] = []
    for tok_tree in tok_trees:
        tokens.extend([Token(
            line = tok.line,
            offset = tok.start,
            text = tok.text,
            tok_type = tok.token_type.name,
            tok_modifiers = [], # no modifiers to begin with
        ) for tok in tok_tree.tokens])
    # __slots__ = ("token_type", "text", "line", "col", "start", "end", "comments")

    data = []
    # tokens = server.tokens.get(document_uri, [])

    for token in tokens:
        log(token)
        # Token(line=12, offset=228, text='col0_1', tok_type='VAR', tok_modifiers=[])
        # Token(line=<Token token_type: TokenType.VAR, text: col0_1, line: 12, col: 36, start: 228, end: None, comments: []>, 
        # offset=238, text='JOIN', tok_type='JOIN', tok_modifiers=[])
        # bullshit! thats not a line number.

        data.extend(
            [
                token.line,
                token.offset,
                len(token.text),
                token_type_names.index(token.tok_type), # returns index into token_type_names
                reduce(operator.or_, token.tok_modifiers, 0), # returns bitmap into modifier_names
            ]
        )

    return t.SemanticTokens(data=data)



# get tokens
# loop over tokens and color by TokenType
# indications of nullability, triggers, checks and no-access comes later and elsewhere.
# autocompletion is later and elsewhere.
# embddedment is also later and elsewhere.
# hinting autogenerated text is in another file. it can also be toggled on/off in settings

# ----------- colors -------------
# keywords, identifiers, parameter (e.g. var), literals, strings, comments, types, 
# comma, brackets, operators, functions, errors, default for unrecognized
# evt. give separate colors to schema, tree, table, column, view, aliases
# 

# ----------- ChatGPT suggests ----------- #
# Bad Token: #FF0000 (bright red) – typically indicates errors or invalid tokens.
# Braces: #A9B7C6 (light gray-blue) – for {} characters.
# Brackets: #A9B7C6 (light gray-blue) – for [] characters.
# Column: #9876AA (light purple) – for database column names.
# Comma: #A9B7C6 (light gray-blue) – for commas , in code.
# Comment: #808080 or #629755 (grayish-green) – for comments in SQL or other code.
# Database Object: #CC7832 (orange) – for database objects such as tables, views, etc.
# Dot: #A9B7C6 (light gray-blue) – for dots . in expressions.
# External Command: #9876AA (light purple) – for external references or commands.
# Keyword: #CC7832 (orange) – for SQL keywords like SELECT, FROM, WHERE.
# Label: #E8BF6A (light yellow) – for labels used in procedures or loops.
# Number Token: #6897BB (light blue) – for numeric literals like 123, 1.23.
# Outer Query Column: #9876AA (light purple) – for columns used in outer queries.
# Parameter: #9876AA (light purple) – for SQL parameters (e.g., in prepared statements).
# Parenthesis: #A9B7C6 (light gray-blue) – for () characters.
# Procedure or Function: #FFC66D (light orange) – for procedure or function names.
# Schema: #9876AA (light purple) – for schema names in fully qualified names.
# Semicolon: #A9B7C6 (light gray-blue) – for semicolons ; in SQL or other code.
# String Token: #6A8759 (green) – for string literals like 'text', "text".
# Synthetic Entity: #A9B7C6 (light gray-blue) – for system-generated entities.
# Table: #FFC66D (light orange) – for table names in SQL queries.
# Table or Columns Alias: #9876AA (light purple) – for aliases in SQL queries.
# Type: #CC7832 (orange) – for SQL types like VARCHAR, INT, DATE.
# Variable: #9876AA (light purple) – for variables in SQL procedures or scripts.

