import operator
from functools import reduce
from enum import IntFlag, auto
from lsprotocol import types as t
from tools.server import server, serverType
from sapi import _editor_tok
from dataclasses import dataclass
from tools.log import log
from tools.settings import Settings
from tools.error import handle_error

class _TokenModifier(IntFlag):
    definition = auto()

@dataclass
class _EditorToken:
    delta_line: int
    delta_offset: int
    text: str
    type_str: str
    modifiers: list[_TokenModifier]


@server.feature(
    t.TEXT_DOCUMENT_SEMANTIC_TOKENS_FULL,
    t.SemanticTokensLegend(token_types=_editor_tok.token_type_names(), 
                           token_modifiers=[m.name for m in _TokenModifier])
    )
def semantic_tokens_full(_: serverType, params: t.SemanticTokensParams) -> t.SemanticTokens | None:
    """Return the semantic tokens for the entire document"""
    # repeated code
    document_uri = params.text_document.uri
    if not document_uri.endswith('.sapi'):
        return None
    document = server.workspace.get_text_document(document_uri)
    # repeated code
    fal_settings = Settings.try_load()
    if handle_error(fal_settings):
        return None
    database_name = fal_settings.current_database
    database = fal_settings.databases[database_name]
    dialect = database.dialect

    sapi_code = document.source
    
    line_start_indices = _line_start_indices(document.lines)

    tokens = dialect.sqlglot_dialect().tokenize(sapi_code)
    tokens_: list[_EditorToken] = []
    last_line = 0
    last_offset = 0
    log([' '.join([f"{t.text}" for t in tokens])])
    for tok in tokens:
        line = tok.line - 1
        log(len(line_start_indices), line, tok)
        # evt. bail out on line == len(line_start_indices)
        
        line_start_index = line_start_indices[line] if line > 0 else 0
        offset = (tok.start - 0) - line_start_index
        if offset < 0:
            log(tok.start, line_start_index, line, line_start_indices)
            raise Exception("offset < 0")

        _delta_line = line - last_line
        _delta_offset = offset - last_offset if _delta_line == 0 else offset
        if _delta_line < 0:
            raise Exception("_delta_line < 0")
        if _delta_offset < 0:
            raise Exception("_delta_offset < 0")

        tok_ = _EditorToken(
            delta_line = _delta_line,
            delta_offset = _delta_offset,
            text = sapi_code[tok.start : tok.end + 1], # tok.text,
            type_str = _editor_tok.get_group_names(tok.token_type),
            modifiers = [], # no modifiers to begin with
            )
        tokens_.append(tok_)
        if last_line > line:
            raise Exception(f"{last_line} > {line}")# or {last_offset} > {offset}")
        last_line = line
        last_offset = offset

    data = []
    for tok_ in tokens_:
        data.extend([
            tok_.delta_line,
            tok_.delta_offset,
            len(tok_.text),
            _editor_tok.token_type_names().index(tok_.type_str), # returns index into token_type_names
            reduce(operator.or_, tok_.modifiers, 0), # returns bitmap into modifier_names
        ])
    log('\n')

    return t.SemanticTokens(data=data)



def _line_start_indices(lines: list[str]) -> list[int]:
    line_start_indices = []
    last_line_length = 0
    current_line_start_index = 0
    for line in lines:
        current_line_start_index += last_line_length
        line_start_indices.append(current_line_start_index)
        last_line_length = len(line)#.strip('\n\r'))# + 1
    return line_start_indices




# get tokens
# loop over tokens and color by TokenType
# indications of nullability, triggers, checks and no-access comes later and elsewhere.
# autocompletion is later and elsewhere.
# embddedment is also later and elsewhere.
# hinting autogenerated text is in another file. it can also be toggled on/off in settings

# ----------- colors -------------
# keywords, identifiers, parameter (e.g. var), literals, strings, comments, types, 
# comma, brackets, operators, functions, errors, default for unrecognized
# evt. give separate colors to schema, tree, table, column, view, aliases
# 

# ----------- ChatGPT suggests ----------- 
"""
Bad Token:        #FF0000 (bright red) 
Braces:           #A9B7C6 (light gray-blue) 
Brackets:         #A9B7C6 (light gray-blue) 
Column:           #9876AA (light purple)
Comma:            #A9B7C6 (light gray-blue) 
Comment:          #808080 or #629755 (grayish-green)
Database Object:  #CC7832 (orange)
Dot:              #A9B7C6 (light gray-blue) 
External Command: #9876AA (light purple) 
Keyword:          #CC7832 (orange)
Label:            #E8BF6A (light yellow)
Number Token:     #6897BB (light blue) 
Outer Query Col:  #9876AA (light purple)
Parameter:        #9876AA (light purple)
Parenthesis:      #A9B7C6 (light gray-blue) 
Routine:          #FFC66D (light orange)
Schema:           #9876AA (light purple)
Semicolon:        #A9B7C6 (light gray-blue) 
String Token:     #6A8759 (green)
Synthetic Entity: #A9B7C6 (light gray-blue)
Table:            #FFC66D (light orange)
Alias:            #9876AA (light 
Type:             #CC7832 (orange) 
Variable:         #9876AA (light purple)

"""



# ----------- Junk ----------- #

    # tok_trees = sapi.parse(sapi_query, fal_dataModel.ok, list[TokenTree]) # try-parse

    ## get tokens from tok_trees
    # tokens: list[Token_] = []
    # last_line = 0
    # last_offset = 0
    # for tok_tree in tok_trees: # should tok trees be sorted?
    #     log(f"tok_tree: {tok_tree.line}, {tok_tree.start}")
    #     log([' '.join([f"{t.text}" for t in tok_tree.tokens])])
    #     for tok in tok_tree.tokens:
    #         log(f"{tok.token_type.name}: {tok.text}, {tok.line}, {tok.start}")
    #         tok_ = Token_(
    #             delta_line = tok.line - last_line,
    #             delta_offset = tok.start - last_offset,
    #             text = tok.text,
    #             tok_type = _keyword_str if tok.token_type in tokenizer._keywords else tok.text,
    #             tok_modifiers = [], # no modifiers to begin with
    #             )
    #         tokens.append(tok_)
    #         if last_line > tok.line or last_offset > tok.start:
    #             raise Exception(f"{last_line} > {tok.line} or {last_offset} > {tok.start}")
    #         last_line = tok.line
    #         last_offset = tok.start
            
        # tokens.extend([Token_(
        #     delta_line = tok.line,
        #     delta_offset = tok.start,
        #     text = tok.text,
        #     tok_type = _keyword_str if tok.token_type in _keywords else tok.text,
        #     tok_modifiers = [], # no modifiers to begin with
        # ) for tok in tok_tree.tokens])
    # __slots__ = ("token_type", "text", "line", "col", "start", "end", "comments")

        # log(token)
        # Token(line=12, offset=228, text='col0_1', tok_type='VAR', tok_modifiers=[])
        # Token(line=<Token token_type: TokenType.VAR, text: col0_1, line: 12, col: 36, start: 228, end: None, comments: []>, 
        # offset=238, text='JOIN', tok_type='JOIN', tok_modifiers=[])
        # bullshit! thats not a line number.
        
        # _keyword_str if tok.token_type in _keywords else tok.text
                        # Token(
                        #     line=current_line - prev_line,
                        #     offset=current_offset - prev_offset,
                        #     text=match.group(0),
                        #     tok_
                                # if tok_.tok_type_str  == _keyword_str:
        #     a = (
        #         tok_.delta_line,
        #         tok_.delta_offset,
        #         len(tok_.text),
        #         token_type_names.index(tok_.tok_type_str), # returns index into token_type_names
        #         reduce(operator.or_, tok_.tok_modifiers, 0), # returns bitmap into modifier_names)}, {tok.line}, {tok.start}")
        #     )
        #     log(f"{tok_.tok_type_str}: {tok_.text}, {a}")
        # # log(f"{tok_.tok_type}: {tok_.tok_type in token_type_names} "
        # #     f"{tok_.tok_type.lower() in token_type_names} {tok_.tok_type.upper() in token_type_names}")
