import yaml
import json
from textwrap import dedent
from pathlib import Path
from pydantic import BaseModel
from sapi import dialect
import sapi
from .error import with_error_message

_primitive = None | bool | int | float | str
# _JsonishValue =      _primitive | list[_primitive] | list['_Jsonish'] | dict[str, '_JsonishValue']
# _Jsonish = dict[str, _primitive | list[_primitive] | list['_Jsonish'] | dict[str, '_JsonishValue']]

_databases: dict[str, sapi.Database] = {} # init in _init_databases_from_settings


class _DatabaseParams(BaseModel):
    connection_info: dict[str, _primitive]
    # dialect starts out as a str, then it gets processed into a Dialect. 
    dialect: str #|dialect.Dialect
    startup_script: str = ""
    sapi_sys_schema: str = "sapi_sys"
    commit_policy: str

class _Settings(BaseModel):
    current_database: str
    show_autogenerated_sql: bool | list[str]
    databases: dict[str, _DatabaseParams]


def load_database(database_name: str = None) -> sapi.Database:
    "This function should be optimized."
    settings = _load()
    _init_databases_from_settings(settings)
    if database_name is None:
        database_name = settings.current_database
    return _databases[database_name]

def load_datamodel(database_name: str = None) -> sapi.DataModel:
    database = load_database(database_name)
    with sapi.Transaction(database) as tr:
        sapi.setup_sapi(database.dialect, tr.cursor(), database.sapi_sys_schema)
    return database.data_model()

def show_autogenerated_sql(uri: str) -> bool: 
    show = _load().show_autogenerated_sql
    if isinstance(show, bool): 
        return show
    return any(uri.endswith(file_type) for file_type in show) 


def _load() -> _Settings:
    setting_files = [
        '.vscode/sapi_settings.yml',  'sapi_settings.yml',
        '.vscode/sapi_settings.yaml', 'sapi_settings.yaml',
        '.vscode/sapi_settings.json', 'sapi_settings.json',
        ]
    setting_files = [f for f in setting_files if Path(f).exists()]
    
    if len(setting_files) > 1:
        raise Exception(f"Expected exactly one sapi_settings file, found multiple: {setting_files}")
    if len(setting_files) == 0:
        raise Exception("Expected a sapi_settings.yml, sapi_settings.yaml or sapi_settings.json file at "
                        "the project root directory or in a .vscode folder.\n"
                        "Found no such file.")

    setting_file = setting_files[0]
    with open(setting_file) as f: # can raise
        setting_data: dict = json.load(f) if setting_file.endswith('json') else yaml.safe_load(f) # can raise
    
    settings = with_error_message(lambda: _Settings(**setting_data), 
        message="The sapi settings file lacks required variables.") # can raise
    _resolve_file_reference(settings) # can raise
    return settings



def _resolve_file_reference(settings: _Settings):
    for name, db in settings.databases.items():
        password = _read_password_from_file(db.connection_info) # can raise
        settings.databases[name].connection_info['password'] = password
        settings.databases[name].connection_info.pop('password_file', None) # the seconds argument, prevents a raise

        # dialect_str: str = db.dialect
        # settings.databases[name].dialect = dialect.get_or_raise(dialect_str) # can raise


def _read_password_from_file(connection_info: dict[str, _primitive]):
    "read from password file with lots of errorhandling."

    con_keys = list(connection_info.keys())
    if 'password' in con_keys and 'password_file' in con_keys:
        raise Exception("The connection_info for the databases in sapi_settings may either contain "
                        "a key 'password' or a key 'password_file', (which points to a file containing "
                        "the password) or neither, but not both.")
    if 'password_file' not in con_keys:
        return None
    password_file: str = connection_info['password_file']
    if not password_file.endswith('.txt'):
        raise Exception(f"password_file should be a txt file. Found {password_file}.")
    with open(password_file, 'r') as f:
        password = f.readline() # get password
        incorrect_extra_line = f.readline()
        if incorrect_extra_line or not password: # check that this behaves right
            raise Exception(f"password_file should contain exactly one line (with the password). No more and no less.")
        if password.strip(' \t') != password:
            raise Exception(F"Password should not have leading or trailing whitespace (i.e.).")
        password = password.strip('\r') # fck carriage return. We won't hold the user responsible for that windows BS.
    return password


def _init_databases_from_settings(settings: _Settings):
    _databases.clear()
    for name, db_params in settings.databases.items():
        
        _databases[name] = sapi.Database(
            dialect=dialect.get_or_raise(db_params.dialect), # can raise
            startup_script=db_params.startup_script,
            connect_kwargs=db_params.connection_info,
            commit_policy=sapi.CommitPolicy.__members__[db_params.commit_policy],
            sapi_sys_schema=db_params.sapi_sys_schema,
            )

