import os
from textwrap import dedent
from lsprotocol import types as t
from tools.server import server
from tools.log import log
from sapi._editor import TokenTree, common_select_clauses
from tools import settings, error
from tools.embedding import Section
import sapi


@server.feature(t.TEXT_DOCUMENT_INLAY_HINT)
@error.as_log_and_popup
def inlay_hints(params: t.InlayHintParams) -> list[t.InlayHint]:
    uri = params.text_document.uri
    if not any(uri.endswith(file_type) for file_type in server.file_types()): return []
    if not settings.show_autogenerated_sql(): return []

    r = params.range
    sections = server.sapi_sections(uri, use_os_line_ending=True) # Range has been is ignored. Bring it back. [r.start.line : r.end.line + 1]
    # lines = server.sapi_lines(uri, True) # [r.start.line : r.end.line + 1]
    return inlay_hints_work(sections)



# def inlay_hints_work(sections: list[Section]) -> list[t.InlayHint]:
#     if sections == []: return []
#     sapi_code = ''.join([s.leading_whitespace + s.query for s in sections])
#     lines = [line for line in sapi_code.split(os.linesep)] 

#     dataModel = settings.load_datamodel() # what if there are multiple datamodels in use ?
#     try:
#         sql_token_trees = sapi.parse(sapi_code, dataModel, list[TokenTree])
#     except Exception as e: # create a user error class for the parser and filter by it
#         code_start = sapi_code if len(sapi_code) < 10 else sapi_code[:10] + '...'
#         log(f"Failed to parse ['''{code_start}''']:\nError: {e}")
#         return []
    
#     line_start_indices = _line_start_indices(lines)
#     hints = []
#     for tok_tree in sql_token_trees:
#         hints.extend(_hints_for_tok_tree(tok_tree, line_start_indices))
#     return hints

def inlay_hints_work(sections: list[Section]) -> list[t.InlayHint]:
    if sections == []: return []
    hints = []
    for s in sections:
        hints.extend(_hints_for_section(s))
    return hints
    

def _hints_for_section(section: Section) -> list[t.InlayHint]:
    sapi_code = os.linesep * section.line_nr_start + ' ' * section.char_start + dedent(section.query)
    lines = [line for line in sapi_code.split(os.linesep)] 

    dataModel = settings.load_datamodel() # what if there are multiple datamodels in use ?
    try:
        sql_token_trees = sapi.parse(sapi_code, dataModel, list[TokenTree])
    except Exception as e: # create a user error class for the parser and filter by it
        code_start = sapi_code if len(sapi_code) < 10 else sapi_code[:10] + '...'
        log(f"Failed to parse ['''{code_start}''']:\nError: {e}")
        return []
    
    line_start_indices = _line_start_indices(lines)
    # unindented_start_indices = _line_start_indices([line.lstrip(' ') for line in lines] )
    # indentions = _indentions(lines)
    hints = []
    for tok_tree in sql_token_trees:
        hints.extend(_hints_for_tok_tree(tok_tree, line_start_indices, lines))
    return hints


def _hints_for_tok_tree(tok_tree: TokenTree, line_start_indices: list[int], lines: list[str]) -> list[t.InlayHint]:
    str_replacements = tok_tree.recursive_str_replacements() # collect replacements in subtrees
    if not str_replacements:
        return [] # handle the None case
    
    hints = []
    put_on_new_line_sequence_len = 0 # used to put join_clauses on seperate lines.
    str_replacements.sort(key = lambda r: r.str_from)
    for rep in str_replacements:
        if not rep.new_tokens:
            continue
        put_on_new_line = rep.new_tokens[0].type in common_select_clauses()
        put_on_new_line_sequence_len = put_on_new_line_sequence_len + 1 if put_on_new_line else 0
        line_nr, char = _line_nr_and_char(rep.str_to, lines, line_start_indices)
        line_nr += put_on_new_line_sequence_len

        prefix = '' if put_on_new_line else ' '
        hint_text = prefix + ' '.join([t.text for t in rep.new_tokens])

        hint = t.InlayHint(
            label=hint_text,
            kind=t.InlayHintKind.Type,
            padding_left=True,
            padding_right=True,
            position=t.Position(line=line_nr, character=char),
            )
        hints.append(hint)

    return hints


# this function looks slow. Evt. use something like binary search.
def _line_nr_and_char(rep_str_to: int, lines: list[str], line_start_indices: list[int]) -> tuple[int, int]:
        # This loop will find line_nr, char if the generated code goes at the beginning of a line (up to indention)
        index = rep_str_to # index for end of generated code. It ends where it begins, since it is inserted 
                           # into preexisting code, rather than replacing it.
        for line_nr, line in enumerate(lines):
            start_index = line_start_indices[line_nr]
            if line_start_indices[line_nr + 1] < index: 
                continue # skipping earlier lines
            if index < start_index: 
                break # skipping later lines

            # Calculate indention
            # This allows us to check, if the hint goes at the start of the unindented line.
            # it is also used to set char = indention
            indention = 0
            for char in line: 
                if char == ' ': indention += 1
                if char == '\t': indention += 4
                else: continue

            if index < start_index or index > start_index + indention:
                continue # 

            # Calculate number of preceeding blank lines
            # This is used to prevent join clauses from skipping newlines and 
            # mix with the code, that should come after the from clause
            prior_blank_line_count = 0
            blank = False
            i = 1
            while i <= line_nr:
                blank = (lines[line_nr - i].strip() == '')
                if not blank: break
                prior_blank_line_count += 1
                i += 1
            
            # decrement by 1 to fix the fact that rep-str_to points to the token on the next line
            # decrement by prior_blank_line_count to prevent join clauses from skipping newlines
            line_nr -= (1 + prior_blank_line_count) # 
            char = indention
            return line_nr, char
        
        # if the generated code is not at the beginning of a line, then we round index
        # down to nearest line_start_index to get line_nr
        line_nr, line_start_index = _round_down_to_nearest_element(index, line_start_indices)
        char = index - line_start_index #if not put_on_new_line else 0
        error.dev_assert(char >= 0, f"char = {char} = {index} - {line_start_index} at line_nr = {line_nr}")
        return line_nr, char


def _round_down_to_nearest_element(number: int, sorted_list: list[int]) -> tuple[int, int] | tuple[None, None]:
    """
    Found target down to the nearest element in the list in log time.
    Returns None if target < sorted_list[0]
    Returns the index and value of the rounded down.
    """
    left = 0 
    right = len(sorted_list) - 1
    nearest_lower_value = None
    idx = None
    mid = None # resulting index
    while left <= right:
        mid = left + (right - left) // 2
        if sorted_list[mid] <= number:
            nearest_lower_value = sorted_list[mid] # update the result
            idx = mid
            left = mid + 1  # search in the right half
        else:
            right = mid - 1  # search in the left half
    
    return idx, nearest_lower_value



def _line_start_indices(lines: list[str]) -> list[int]:
    line_start_indices = []
    last_line_length = 0
    current_line_start_index = 0
    for line in lines:
        current_line_start_index += last_line_length
        line_start_indices.append(current_line_start_index)
        last_line_length = len(line) + len(os.linesep)
    return line_start_indices




# if possible, try to make room for hints by carefully adding / removing new lines 


r"""
what if there are multiple datamodels in use ?

sapi in different sections are mistanken treated as part of the same statement, du to 
    sapi_code = ''.join([s.leading_whitespace + s.query for s in sections])
"""

