from lsprotocol import types as t
from tools.server import server
from tools.log import log
from sapi._editor import TokenTree, common_select_clauses
from tools import settings
from tools import error
import sapi


@server.feature(t.TEXT_DOCUMENT_INLAY_HINT)
@error.as_log_and_popup
def inlay_hints(params: t.InlayHintParams) -> list[t.InlayHint]:
    uri = params.text_document.uri
    if not any(uri.endswith(file_type) for file_type in server.file_types()): return []
    if not settings.show_autogenerated_sql(): return []

    r = params.range
    lines = server.sapi_lines(uri)[r.start.line : r.end.line + 1]
    return inlay_hints_work(lines)


def inlay_hints_work(lines: list[str]) -> list[t.InlayHint]:
    if lines == []: return []
    sapi_code = '\r\n'.join([line.strip('\n\r') for line in lines]) # does this work for multiple queries?
    dataModel = settings.load_datamodel()
    try:
        sql_token_trees = sapi.parse(sapi_code, dataModel, list[TokenTree])
    except Exception as e: # create a user error class for the parser and filter by it
        code_start = sapi_code if len(sapi_code) < 10 else sapi_code[:10] + '...'
        log(f"Failed to parse ['''{code_start}''']:\nError: {e}")
        return []
    
    line_start_indices = _line_start_indices(lines)
    hints = []
    for tok_tree in sql_token_trees:
        hints.extend(_get_hints(tok_tree, line_start_indices))
    return hints


def _get_hints(tok_tree: TokenTree, line_start_indices: list[int]) -> list[t.InlayHint]:
    str_replacements = tok_tree.recursive_str_replacements() # collect replacements in subtrees
    if not str_replacements:
        return [] # handle the None case
    
    hints = []
    put_on_new_line_sequence_len = 0 # used to put join_clauses on seperate lines.
    str_replacements.sort(key = lambda r: r.str_from_)
    for rep in str_replacements:
        if not rep.new_tokens:
            continue
        put_on_new_line = rep.new_tokens[0].type in common_select_clauses()
        prefix = '' if put_on_new_line else ' '
        hint_text = prefix + ' '.join([t.text for t in rep.new_tokens])

        index = rep.str_to # hints goes after replaced code. This is relevant for "join tree on ..." followed by hint.
        line_nr, line_start_index = _round_down_to_nearest_element(index, line_start_indices)
        char = index - line_start_index
        error.dev_assert(char >= 0, f"char = {char} = {index} - {line_start_index}")
        line_nr += put_on_new_line_sequence_len

        hint = t.InlayHint(
            label=hint_text,
            kind=t.InlayHintKind.Type,
            padding_left=True,
            padding_right=True,
            position=t.Position(line=line_nr, character=char),
            )
        hints.append(hint)

        put_on_new_line_sequence_len = put_on_new_line_sequence_len + 1 if put_on_new_line else 0

    return hints



def _line_start_indices(lines: list[str]) -> list[int]:
    line_start_indices = []
    last_line_length = 0
    current_line_start_index = 0
    for line in lines:
        current_line_start_index += last_line_length
        line_start_indices.append(current_line_start_index)
        last_line_length = len(line)
    return line_start_indices



def _round_down_to_nearest_element(number: int, sorted_list: list[int]) -> tuple[int, int] | tuple[None, None]:
    """
    Found target down to the nearest element in the list in log time.
    Returns None if target < sorted_list[0]
    Returns the index and value of the rounded down.
    """
    left = 0 
    right = len(sorted_list) - 1
    nearest_lower_value = None
    idx = None
    mid = None # resulting index
    while left <= right:
        mid = left + (right - left) // 2
        if sorted_list[mid] <= number:
            nearest_lower_value = sorted_list[mid] # update the result
            idx = mid
            left = mid + 1  # search in the right half
        else:
            right = mid - 1  # search in the left half
    
    return idx, nearest_lower_value




# if possible, try to make room for hints by carefully adding / removing new lines 


r"""

hints are placed incorrectly
----

--- ARGS, KWARGS --- (for error.as_log_and_popup decorated function)
(InlayHintParams(text_document=TextDocumentIdentifier(uri='file:///c%3A/Mine/Python/_Sandbox/dib.sapi'), range=0:0-5:0, work_done_token=None),) {} 

Traceback (most recent call last):
  File "c:\Users\flem1\.vscode\extensions\fch.sapi-0.0.0\server\tools\error.py", line 21, in new_func
    return old_func(*args, **kwargs)
  File "c:\Users\flem1\.vscode\extensions\fch.sapi-0.0.0\server\features\hinting.py", line 20, in inlay_hints
    return inlay_hints_work(lines)
  File "c:\Users\flem1\.vscode\extensions\fch.sapi-0.0.0\server\features\hinting.py", line 26, in inlay_hints_work
    sql_token_trees = sapi.parse(sapi_code, dataModel, list[TokenTree])
  File "C:\Mine\Python\Sapi\Parser\src\sapi\_internals\parser.py", line 25, in parse
    sql_token_trees.append(_parse_token_tree(sapi_tok_tree))
  File "C:\Mine\Python\Sapi\Parser\src\sapi\_internals\parser.py", line 54, in _parse_token_tree
    token_tree = select_parser.parse_select(token_tree) # this only changes the leaf tokens
  File "C:\Mine\Python\Sapi\Parser\src\sapi\_internals\select_\select_parser.py", line 7, in parse_select
    tree_joins = select_analyzer.find_tree_joins(DynLoop(token_tree))
  File "C:\Mine\Python\Sapi\Parser\src\sapi\_internals\select_\select_analyzer.py", line 14, in find_tree_joins
    tree_join, on_clause_tables_in_join = _make_tree_join(loop, [j.tree_tok for j in tree_joins])
  File "C:\Mine\Python\Sapi\Parser\src\sapi\_internals\select_\select_analyzer.py", line 34, in _make_tree_join
    raise ParserError("expected identifier or variable after from / join.")
sapi._internals.token_tree.ParserError: expected identifier or variable after from / join.



----
error tree [hint(tab20)] is displayed incorrect. Hint is on newline


"""

