[package]
name = "sapi_rust_app"
version = "0.1.0"
edition = "2021"

[dependencies]
sapi_compiler = { path = "../../sapi_compiler" }
bumpalo = { version = "3.16.0", features = [ "collections", "boxed" ] } # should not be necessary


# [[bin]]
# name = "sandbox"
# path = "src/sandbox.rs"



