{
    "comments": { # used for comment-toggling
      "lineComment": "//",
      "blockComment": ["/*", "*/"]
    },
    "brackets": [ # highlight braket beneath cursor and its matching pair
      ["{", "}"],
      ["[", "]"],
      ["(", ")"]
    ],
    "autoClosingPairs": [ #
      ["{", "}"], # if "notIn" aren't required, then the syntax may be simplified
      { "open": "[", "close": "]" },
      { "open": "(", "close": ")" },
      { "open": "\"", "close": "\"", "notIn": ["string", "comment"] },
      { "open": "'", "close": "'", "notIn": ["string", "comment"] }
    ],
    "surroundingPairs": [ # surrounds selected text with open-close pair, if the opener is typed
      { "open": "{", "close": "}" },
      { "open": "[", "close": "]" },
      { "open": "(", "close": ")" },
      { "open": "\"", "close": "\"" },
      { "open": "'", "close": "'" }
    ],
    "folding": { # folding on indent is applied no matter what. The markers are an addition.
      "markers": {
        "start": "^\\s*//\\s*#?region\\b", # evt. start with query begin keyword
        "end": "^\\s*//\\s*#?endregion\\b" # end on ;
      }
    },
    # "onEnterRules": [
    #   {
    #     "beforeText": "^\\s*(\\{|\\[|\\().*?[^\\}]\\s*$", 
    #     "action": { "indent": "indent" }
    #   }
    # ],
    "wordPattern": "\\w+"
  }