from sapi._internals.db_contact.data_model import DataModel
from sapi._internals.token_tree import TokenTree
from sapi._internals.db_contact.pep249_database_api_spec_v2 import Cursor




def generate_insert(tree_name: str, data: dict) -> TokenTree:
    ...
    # get tab-name for root-of-data 
    # insert_into_tree(tab, data)



# def insert_into_tree(tree_name: str, data: list[dict], data_model: DataModel):
def insert_into_tree(root: str, data: list[dict]|dict):
    if isinstance(data, dict):
        data = [data]
    pickup = _recursive_insert_into_tree([], root, data, None, None)
    return pickup
    # hyp return the ids, or perhaps just the top level id?

def insert_into_tree_1(cur: Cursor, root: str, data: list[dict]|dict):
    if isinstance(data, dict):
        data = [data]
    _recursive_insert_into_tree(cur, root, data, [], None)
    # hyp return the ids, or perhaps just the top level id?


# remarkable: it doesnt even use the FK data in the tree / datamodel. 
# It just uses the structure of the hierachical data itself.
# hmm: the data structure might serve as error checking.
# This can be parralized
# make an out parameter which can either be None or query_list: list[str] or ids: dict[str, int|recursion]
# query_list without execution would require calculating ids manually
# test insert into subtree with parent as foreign key literal
# handle user defined name of id
def _recursive_insert_into_tree_1(cur: Cursor, tab_name: str, data: list[dict], parent_ids: list[int], parent_id_name: str):
    if data == []: 
        return # evt. return query, args
    assert bool(parent_id_name) == bool(parent_ids), ""
    # check that tab_name is alphanumeric

    args = []
    query = "" # hyp: find a suitable stream type for performance
    def is_subtree(var): return isinstance(var, list) and (var == [] or isinstance(var[0], dict))

    # build query and args
    first_row = dict(data[0])
    if parent_ids:
        first_row[parent_id_name] = parent_ids[0]
        
    query += f"insert into {tab_name} (" 
    query += ', '.join([col for col, datum in first_row.items() if not is_subtree(datum)])
    query += ") values\n"

    arg_count = len([d for d in first_row.values() if not is_subtree(d)]) 
    piece = '(' + ('%s, ' * arg_count).rstrip(', ') + ')'
    row_count = len(data)
    for i, row in enumerate(data):
        query += piece + (',\n' if i == row_count else '\n')
        # line assumes that the foreign keys are not given in advance, but must be autogenerated.
        args += [d for d in row.values() if not is_subtree(d)]
        if parent_ids:
            args.append(parent_ids[i])
        # if you need to allow fk in the input, then you can use fk_in_row_i = list(d.values())[i][id_name]
    id_name = tab_name + '_id' # handle user defined name of id
    # optionally quit the returning clause for the leaves
    query += f"returning {id_name};\n" # non-postgress databases will need something different here.

    # execute
    # print(_put_args_into_query(query, args))
    
    cur.execute(query, args)
    ids: list[int] = [id_row[0] for id_row in cur.fetchall()]
    assert len(ids) == len(data), ""

    # convert data from hierachical to sql format
    children_names = [k for k, v in first_row.items() if is_subtree(v)]
    if children_names == []:
        return
    children_data = {k: [] for k in children_names}
    for row in data:
        for child in children_names:
            child_data = row[child]
            assert is_subtree(child_data), ""
            children_data[child] += child_data
    # recursion
    for child in children_names:
        child_data = children_data[child]
        _recursive_insert_into_tree(cur, child, child_data, ids, id_name)

_Pickup = list[tuple[str, list]] # list of (query, args)
def _recursive_insert_into_tree(pickup: _Pickup, tab_name: str, data: list[dict], parent_ids: list[int], parent_id_name: str) -> _Pickup:
    if data == []: 
        return pickup
    # assert bool(parent_id_name) == bool(parent_ids), ""
    # check that tab_name is alphanumeric

    args = []
    query = "" # hyp: find a suitable stream type for performance
    def is_subtree(var): return isinstance(var, list) and (var == [] or isinstance(var[0], dict))

    # build query and args
    columns = [col for col, datum in data[0].items() if not is_subtree(datum)]
    first_row = dict(data[0])
    if parent_id_name:
        # first_row[parent_id_name] = None # parent_ids[0]
        columns = [parent_id_name] + columns
        parent = parent_id_name.split('_id')[0]
        query += f"with parent as (select max({parent_id_name}) as id from {parent})\n"
    query += f"insert into {tab_name} (" 
    query += ', '.join(columns)
    query += ")\n"

    arg_count = len([d for d in data[0].values() if not is_subtree(d)]) 
    piece = 'select ' 
    if parent_id_name: piece += 'parent.id, '
    piece += '%s, ' * arg_count
    piece = piece.rstrip(', ')
    if parent_id_name: piece += ' from parent '
    last_index = len(data) - 1
    for i, row in enumerate(data):
        query += piece + ('union\n' if i < last_index else '\n')
        # line assumes that the foreign keys are not given in advance, but must be autogenerated.
        args += [d for d in row.values() if not is_subtree(d)]
        # if parent_ids:
        #     args.append(parent_ids[i])
        # if you need to allow fk in the input, then you can use fk_in_row_i = list(d.values())[i][id_name]
    id_name = tab_name + '_id' # handle user defined name of id
    # optionally quit the returning clause for the leaves
    # query += f"returning {id_name};\n" # non-postgress databases will need something different here.

    # execute
    print(_put_args_into_query(query, args))
    pickup.append((query, args))
    
    # cur.execute(query, args)
    # ids: list[int] = [id_row[0] for id_row in cur.fetchall()]
    # assert len(ids) == len(data), ""

    # convert data from hierachical to sql format
    children_names = [k for k, v in data[0].items() if is_subtree(v)]
    if children_names == []:
        return
    children_data = {k: [] for k in children_names}
    for row in data:
        for child in children_names:
            child_data = row[child]
            assert is_subtree(child_data), ""
            children_data[child] += child_data
    # recursion
    for child in children_names:
        child_data = children_data[child]
        pickup.append(_recursive_insert_into_tree(pickup, child, child_data, None, id_name))




def _put_args_into_query(query: str, args: list): # doesnt handle dict args
    for arg in args:
        arg_str = f"'{arg}'" if isinstance(arg, str) else f"{arg}"
        assert '%s' in query, "too few placeholders in query"
        query = query.replace('%s', arg_str, 1)
    assert '%s' not in query, "too many placeholders in query"
    return query




