from sapi._internals.db_contact.data_model import DataModel
from sapi._internals.token_tree import TokenTree
from sapi._internals.db_contact.pep249_database_api_spec_v2 import Cursor


def insert_into_tree_1(tree_name: str, data: dict, data_model: DataModel):
    # make individual insert returning id
    # find lists inside the data dict
    # for each element of each list
    #     recurse into that element
    ...
    # generate_insert

# def insert_into_tree(tree_name: str, data: list[dict], data_model: DataModel):
def insert_into_tree(cur: Cursor, root: str, data: list[dict]|dict):
    if isinstance(data, dict):
        data = [data]
    _recursive_insert_into_tree(cur, root, data)
    # hyp return the ids, or perhaps just the top level id?


# remarkable: it doesnt even use the FK data in the tree / datamodel. 
# It just uses the structure of the hierachical data itself.
# hmm: the data structure might serve as error checking.
def _recursive_insert_into_tree(cur: Cursor, tab_name: str, data: list[dict]):
    if data == []: 
        return # evt. return query, args

    args = []
    query = "" # hyp: find a suitable stream type for performance
    subtree_type = list[dict] # list of rows, where row is col_name -> cell_data. (nb: subtree_type iss the valu in row_dict whoose key is tab_name)
    temp_subtree_type = list 

    # build query and args
    # args.append(tab_name)
    # check that tab_name is alphanumeric
    query += f"insert into {tab_name} (" # values \n
    query += ', '.join([col for col, datum in data[0].items() if not isinstance(datum, temp_subtree_type)])
    query += ") values\n"

    arg_count = len([d for d in data[0].values() if not isinstance(d, temp_subtree_type)])
    piece = '(' + ('%s, ' * arg_count).rstrip(', ') + ')'
    count = len(data)
    id_name = tab_name + '_id' # handle user defined name of id

    for i, row in enumerate(data):
        # print(f'{i}: {row}')
        query += piece + (',\n' if i == count else '\n')
        # line assumes that the foreign keys are not given in advance, but must be autogenerated.
        args += [d for d in row.values() if not isinstance(d, temp_subtree_type)]
        # if you need to allow fk in the input, then you can use fk_in_row_i = list(d.values())[i][id_name]
    query += f"returning {id_name};\n" # non-postgress databases will need something different here.

    # execute
    # print('---')
    # print(query)
    # print('---')
    # print(args)
    # print('---')
    q = query
    for arg in args:
        arg_str = f"'{arg}'" if isinstance(arg, str) else f"{arg}"
        q = q.replace('%s', arg_str, 1)
    print(q)
    # print('---')
    cur.execute(query, args)
    ids: list[int] = [row[0] for row in cur.fetchall()]
    assert len(ids) == len(data), ""

    # convert data from hierachical to sql format
    children_names = [k for k, v in data[0].items() if isinstance(v, temp_subtree_type)]
    children_data = {k: [] for k in children_names}
    for id, row in zip(ids, data):
        for child in children_names:
            child_data: list[dict] = row[child]
            assert isinstance(child_data, list), ""
            for child_row in child_data: # evt. put this loop into the next recursion step.
                child_row[id_name] = id # connects child to parent. This is a foreign key
            children_data[child] += child_data
    # recursion
    for child in children_names:
        child_data = children_data[child]
        _recursive_insert_into_tree(cur, child, child_data)



def generate_insert(info) -> TokenTree:
    ...
    # hyp: info = tree_name: str, data: dict




