from typing import Any
from sapi._internals.db_contact.pep249_database_api_spec_v2 import Cursor
from sapi._internals.error import QueryError, CompilerError

# ------------- generate insert ------------- #
_Pickup = list[tuple[str, list]] # list of (query, args)

def generate_insert(json: dict[list[dict]]) -> tuple[str, list]:
    if len(json.items()) != 1: raise QueryError(
        f"Expected only one tree or subtree to insert into, but received {list(json.keys())}")
    root = list(json.keys())[0]
    data = list(json.values())[0]
    # if isinstance(data, dict):
    #     data = [data]
    pickup = _recursive_generate_insert([], root, data, None)
    query = ';\n'.join(p[0] for p in pickup)
    args = []
    for p in pickup:
        args += p[1]
    return query, args

def _recursive_generate_insert(pickup: _Pickup, tab_name: str, data: list[dict], parent: str) -> _Pickup:
    if pickup is None: raise CompilerError("ØV!")
    if data == []: return pickup
    # assert tab_name.isascii() and tab_name.replace('_', '').isalnum(), "tab_name should be ascii and alhanumeric"

    query, args = _generate_table_insert(tab_name, data, parent)
    pickup.append((query, args))
    children_data = _from_hieracical_to_sql_format(data)
    for child_name, child_data in children_data.items():
        pickup = _recursive_generate_insert(pickup, child_name, child_data, tab_name)
    return pickup


def _generate_table_insert(tab_name: str, data: list[dict], parent: str) -> tuple[str, list]:
    args = []
    query = "" # hyp: find a suitable stream type for performance

    # build query and args
    columns = [col for col, datum in data[0].items() if not _is_subtree(datum)]
    if parent:
        parent_id_name = parent + '_id'
        columns = [parent_id_name] + columns
        query += f"with parent as (select max({parent_id_name}) as id from {parent})\n"
    query += f"insert into {tab_name} (" 
    query += ', '.join(columns)
    query += ")\n"

    arg_count = len([d for d in data[0].values() if not _is_subtree(d)]) 
    piece = 'select ' 
    if parent: piece += 'parent.id, '
    piece += '%s, ' * arg_count
    piece = piece.rstrip(', ')
    if parent: piece += ' from parent '

    last_index = len(data) - 1
    for i, row in enumerate(data):
        query += piece + ('union\n' if i < last_index else '\n')
        args += [d for d in row.values() if not _is_subtree(d)]

    return query, args


# ------------- insert ------------- #


def insert_into_tree(cur: Cursor, json: dict[list[dict]]):
    if len(json.items()) != 1: raise QueryError(
        f"Expected only one tree or subtree to insert into, but received {list(json.keys())}")
    root = list(json.keys())[0]
    data = list(json.values())[0]
    _recursive_insert_into_tree(cur, root, data, [], None)
    # hyp return the ids, or perhaps just the top level id?


def _recursive_insert_into_tree(cur: Cursor, tab_name: str, data: list[dict], parent_ids: list[int], parent_id_name: str):
    if data == []: 
        return # evt. return query, args
    if bool(parent_id_name) != bool(parent_ids): raise CompilerError("")
    # check that tab_name is alphanumeric

    id_name = tab_name + '_id' # handle user defined name of id
    query, args = _generate_immediate_table_insert(tab_name, data, parent_ids, parent_id_name)

    # execute
    # print(_put_args_into_query(query, args))
    cur.execute(query, args)
    ids: list[int] = [id_row[0] for id_row in cur.fetchall()]
    if len(ids) != len(data): raise CompilerError("")

    children_data = _from_hieracical_to_sql_format(data)
    # recursion
    for child in children_data:
        child_data = children_data[child]
        _recursive_insert_into_tree(cur, child, child_data, ids, id_name)

def _generate_immediate_table_insert(tab_name: str, data: list[dict], parent_ids: list[int], parent_id_name: str):
    args = []
    query = "" # hyp: find a suitable stream type for performance

    # build query and args
    first_row = dict(data[0])
    if parent_ids:
        first_row[parent_id_name] = parent_ids[0]
        
    query += f"insert into {tab_name} (" 
    query += ', '.join([col for col, datum in first_row.items() if not _is_subtree(datum)])
    query += ") values\n"

    arg_count = len([d for d in first_row.values() if not _is_subtree(d)]) 
    piece = '(' + ('%s, ' * arg_count).rstrip(', ') + ')'
    row_count = len(data)
    for i, row in enumerate(data):
        query += piece + (',\n' if i == row_count else '\n')
        # line assumes that the foreign keys are not given in advance, but must be autogenerated.
        args += [d for d in row.values() if not _is_subtree(d)]
        if parent_ids:
            args.append(parent_ids[i])
    id_name = tab_name + '_id' # handle user defined name of id
    # optionally quit the returning clause for the leaves
    query += f"returning {id_name};\n" # non-postgress databases will need something different here.

    return query, args


# ------------- both ------------- #

def _from_hieracical_to_sql_format(data: list[dict[str, Any]]) -> dict[str, list]:
    children_names = [k for k, v in data[0].items() if _is_subtree(v)]
    if children_names == []:
        return {}
    children_data = {k: [] for k in children_names}
    for row in data:
        for child in children_names:
            child_data = row[child]
            if not _is_subtree(child_data): raise CompilerError("")
            children_data[child] += child_data

    return children_data


def _put_args_into_query(query: str, args: list): # only used for debugging
    for arg in args:
        arg_str = f"'{arg}'" if isinstance(arg, str) else f"{arg}"
        if '%s' not in query: raise CompilerError("too few placeholders in query")
        query = query.replace('%s', arg_str, 1)
    if '%s' in query: raise CompilerError("too many placeholders in query")
    return query

def _is_subtree(var): return isinstance(var, list) and (var == [] or isinstance(var[0], dict))



