current_databasesss: demo_database
databases: 
    demo_database:
        dialect: postgres
        # prompt_for_password: False # indicates whether to prompt for password, when firing a query in the editor. 

        # this node must contain a valid set of inputs into the dialect.connect function
        # except that password may be replaced with password_file e.i a txt file 
        # containing the password.
        connection_info:
            host: localhost
            port: 5432
            dbname: postgres
            user: postgres
            # specify eksplicit password or a file containing the password or neither
            # password: 
            password_file: C:\Mine\Python\sapi_secret\pg_password.txt



