

pub enum SapiError {
    QueryError,
    DataModelError,
}

// class CompilerError(Exception): ...
// class QueryError(Exception): ...
// class DataModelError(Exception): ...
// class TestError(Exception): ...

