from enum import Enum, auto
from sqlglot.tokens import TokenType as GlotType
from . import tokenizer

class _TokTypeGroup(Enum):
    # SemiColon = auto() # goes into keyword
    EmbededVariableStart = auto()
    Number = auto()
    Variable = auto() # Identifier
    String = auto()
    Type = auto() # DataType
    Keyword = auto() # Keyword or SemiColon
    Other = auto()

_group_set_by_grouptype: dict[_TokTypeGroup, GlotType] = {}

# _group_set_by_grouptype[_TokTypeGroup.SemiColon] = {GlotType.SEMICOLON}
_group_set_by_grouptype[_TokTypeGroup.EmbededVariableStart] = {GlotType.COLON}
_group_set_by_grouptype[_TokTypeGroup.Number] = {GlotType.NUMBER}

_group_set_by_grouptype[_TokTypeGroup.Variable] = {
    GlotType.IDENTIFIER,
    GlotType.VAR,
    GlotType.PARAMETER,
}

_group_set_by_grouptype[_TokTypeGroup.String] = {
    GlotType.BIT_STRING,
    GlotType.HEX_STRING,
    GlotType.BYTE_STRING,
    GlotType.NATIONAL_STRING,
    GlotType.RAW_STRING,
    GlotType.HEREDOC_STRING,
    GlotType.UNICODE_STRING,
    GlotType.STRING,
}

_group_set_by_grouptype[_TokTypeGroup.Type] = {
    GlotType.BIT,
    GlotType.BOOLEAN,
    GlotType.TINYINT,
    GlotType.UTINYINT,
    GlotType.SMALLINT,
    GlotType.USMALLINT,
    GlotType.MEDIUMINT,
    GlotType.UMEDIUMINT,
    GlotType.INT,
    GlotType.UINT,
    GlotType.BIGINT,
    GlotType.UBIGINT,
    GlotType.INT128,
    GlotType.UINT128,
    GlotType.INT256,
    GlotType.UINT256,
    GlotType.FLOAT,
    GlotType.DOUBLE,
    GlotType.DECIMAL,
    GlotType.DECIMAL32,
    GlotType.DECIMAL64,
    GlotType.DECIMAL128,
    GlotType.UDECIMAL,
    GlotType.BIGDECIMAL,
    GlotType.CHAR,
    GlotType.NCHAR,
    GlotType.VARCHAR,
    GlotType.NVARCHAR,
    GlotType.BPCHAR,
    GlotType.TEXT,
    GlotType.MEDIUMTEXT,
    GlotType.LONGTEXT,
    GlotType.MEDIUMBLOB,
    GlotType.LONGBLOB,
    GlotType.TINYBLOB,
    GlotType.TINYTEXT,
    GlotType.NAME,
    GlotType.BINARY,
    GlotType.VARBINARY,
    GlotType.JSON,
    GlotType.JSONB,
    GlotType.TIME,
    GlotType.TIMETZ,
    GlotType.TIMESTAMP,
    GlotType.TIMESTAMPTZ,
    GlotType.TIMESTAMPLTZ,
    GlotType.TIMESTAMPNTZ,
    GlotType.TIMESTAMP_S,
    GlotType.TIMESTAMP_MS,
    GlotType.TIMESTAMP_NS,
    GlotType.DATETIME,
    GlotType.DATETIME64,
    GlotType.DATE,
    GlotType.DATE32,
    GlotType.INT4RANGE,
    GlotType.INT4MULTIRANGE,
    GlotType.INT8RANGE,
    GlotType.INT8MULTIRANGE,
    GlotType.NUMRANGE,
    GlotType.NUMMULTIRANGE,
    GlotType.TSRANGE,
    GlotType.TSMULTIRANGE,
    GlotType.TSTZRANGE,
    GlotType.TSTZMULTIRANGE,
    GlotType.DATERANGE,
    GlotType.DATEMULTIRANGE,
    GlotType.UUID,
    GlotType.GEOGRAPHY,
    GlotType.NULLABLE,
    GlotType.GEOMETRY,
    GlotType.HLLSKETCH,
    GlotType.HSTORE,
    GlotType.SUPER,
    GlotType.SERIAL,
    GlotType.SMALLSERIAL,
    GlotType.BIGSERIAL,
    GlotType.XML,
    GlotType.YEAR,
    GlotType.UNIQUEIDENTIFIER,
    GlotType.USERDEFINED,
    GlotType.MONEY,
    GlotType.SMALLMONEY,
    GlotType.ROWVERSION,
    GlotType.IMAGE,
    GlotType.VARIANT,
    GlotType.OBJECT,
    GlotType.INET,
    GlotType.IPADDRESS,
    GlotType.IPPREFIX,
    GlotType.IPV4,
    GlotType.IPV6,
    GlotType.ENUM,
    GlotType.ENUM8,
    GlotType.ENUM16,
    GlotType.FIXEDSTRING,
    GlotType.LOWCARDINALITY,
    GlotType.NESTED,
    GlotType.AGGREGATEFUNCTION,
    GlotType.SIMPLEAGGREGATEFUNCTION,
    GlotType.TDIGEST,
    GlotType.UNKNOWN,
    GlotType.VECTOR,
}

_ = {
    GlotType.SEMICOLON,
    GlotType.XOR,
    GlotType.AND,
    GlotType.OR,
    GlotType.BREAK,
    GlotType.DATABASE,
    GlotType.COLUMN,
    GlotType.COLUMN_DEF,
    GlotType.SCHEMA,
    GlotType.TABLE,
    GlotType.WAREHOUSE,
    GlotType.STREAMLIT,
    GlotType.ALIAS,
    GlotType.ALTER,
    GlotType.ALWAYS,
    GlotType.ALL,
    GlotType.ANTI,
    GlotType.ANY,
    GlotType.APPLY,
    GlotType.ARRAY,
    GlotType.ASC,
    GlotType.ASOF,
    GlotType.AUTO_INCREMENT,
    GlotType.BEGIN,
    GlotType.BETWEEN,
    GlotType.CACHE,
    GlotType.CASE,
    GlotType.CHARACTER_SET,
    GlotType.CLUSTER_BY,
    GlotType.COLLATE,
    GlotType.COMMAND,
    GlotType.COMMENT,
    GlotType.COMMIT,
    GlotType.CONNECT_BY,
    GlotType.CONSTRAINT,
    GlotType.COPY,
    GlotType.CREATE,
    GlotType.CROSS,
    GlotType.CUBE,
    GlotType.CURRENT_DATE,
    GlotType.CURRENT_DATETIME,
    GlotType.CURRENT_TIME,
    GlotType.CURRENT_TIMESTAMP,
    GlotType.CURRENT_USER,
    GlotType.DECLARE,
    GlotType.DEFAULT,
    GlotType.DELETE,
    GlotType.DESC,
    GlotType.DESCRIBE,
    GlotType.DICTIONARY,
    GlotType.DISTINCT,
    GlotType.DISTRIBUTE_BY,
    GlotType.DIV,
    GlotType.DROP,
    GlotType.ELSE,
    GlotType.END,
    GlotType.ESCAPE,
    GlotType.EXCEPT,
    GlotType.EXECUTE,
    GlotType.EXISTS,
    GlotType.FALSE,
    GlotType.FETCH,
    GlotType.FILTER,
    GlotType.FINAL,
    GlotType.FIRST,
    GlotType.FOR,
    GlotType.FORCE,
    GlotType.FOREIGN_KEY,
    GlotType.FORMAT,
    GlotType.FROM,
    GlotType.FULL,
    GlotType.FUNCTION,
    GlotType.GLOB,
    GlotType.GLOBAL,
    GlotType.GRANT,
    GlotType.GROUP_BY,
    GlotType.GROUPING_SETS,
    GlotType.HAVING,
    GlotType.HINT,
    GlotType.IGNORE,
    GlotType.ILIKE,
    GlotType.ILIKE_ANY,
    GlotType.IN,
    GlotType.INDEX,
    GlotType.INNER,
    GlotType.INSERT,
    GlotType.INTERSECT,
    GlotType.INTERVAL,
    GlotType.INTO,
    GlotType.INTRODUCER,
    GlotType.IRLIKE,
    GlotType.IS,
    GlotType.ISNULL,
    GlotType.JOIN,
    GlotType.JOIN_MARKER,
    GlotType.KEEP,
    GlotType.KEY,
    GlotType.KILL,
    GlotType.LANGUAGE,
    GlotType.LATERAL,
    GlotType.LEFT,
    GlotType.LIKE,
    GlotType.LIKE_ANY,
    GlotType.LIMIT,
    GlotType.LIST,
    GlotType.LOAD,
    GlotType.LOCK,
    GlotType.MAP,
    GlotType.MATCH_CONDITION,
    GlotType.MATCH_RECOGNIZE,
    GlotType.MEMBER_OF,
    GlotType.MERGE,
    GlotType.MOD,
    GlotType.MODEL,
    GlotType.NATURAL,
    GlotType.NEXT,
    GlotType.NOTNULL,
    GlotType.NULL,
    GlotType.OBJECT_IDENTIFIER,
    GlotType.OFFSET,
    GlotType.ON,
    GlotType.ONLY,
    GlotType.OPERATOR,
    GlotType.ORDER_BY,
    GlotType.ORDER_SIBLINGS_BY,
    GlotType.ORDERED,
    GlotType.ORDINALITY,
    GlotType.OUTER,
    GlotType.OVER,
    GlotType.OVERLAPS,
    GlotType.OVERWRITE,
    GlotType.PARTITION,
    GlotType.PARTITION_BY,
    GlotType.PERCENT,
    GlotType.PIVOT,
    GlotType.PLACEHOLDER,
    GlotType.POSITIONAL,
    GlotType.PRAGMA,
    GlotType.PREWHERE,
    GlotType.PRIMARY_KEY,
    GlotType.PROCEDURE,
    GlotType.PROPERTIES,
    GlotType.PSEUDO_TYPE,
    GlotType.QUALIFY,
    GlotType.QUOTE,
    GlotType.RANGE,
    GlotType.RECURSIVE,
    GlotType.REFRESH,
    GlotType.RENAME,
    GlotType.REPLACE,
    GlotType.RETURNING,
    GlotType.REFERENCES,
    GlotType.RIGHT,
    GlotType.RLIKE,
    GlotType.ROLLBACK,
    GlotType.ROLLUP,
    GlotType.ROW,
    GlotType.ROWS,
    GlotType.SELECT,
    GlotType.SEMI,
    GlotType.SEPARATOR,
    GlotType.SEQUENCE,
    GlotType.SERDE_PROPERTIES,
    GlotType.SET,
    GlotType.SETTINGS,
    GlotType.SHOW,
    GlotType.SIMILAR_TO,
    GlotType.SOME,
    GlotType.SORT_BY,
    GlotType.START_WITH,
    GlotType.STORAGE_INTEGRATION,
    GlotType.STRAIGHT_JOIN,
    GlotType.STRUCT,
    GlotType.SUMMARIZE,
    GlotType.TABLE_SAMPLE,
    GlotType.TAG,
    GlotType.TEMPORARY,
    GlotType.TOP,
    GlotType.THEN,
    GlotType.TRUE,
    GlotType.TRUNCATE,
    GlotType.UNCACHE,
    GlotType.UNION,
    GlotType.UNNEST,
    GlotType.UNPIVOT,
    GlotType.UPDATE,
    GlotType.USE,
    GlotType.USING,
    GlotType.VALUES,
    GlotType.VIEW,
    GlotType.VOLATILE,
    GlotType.WHEN,
    GlotType.WHERE,
    GlotType.WINDOW,
    GlotType.WITH,
    GlotType.UNIQUE,
    GlotType.VERSION_SNAPSHOT,
    GlotType.TIMESTAMP_SNAPSHOT,
    GlotType.OPTION,
}

_group_set_by_grouptype[_TokTypeGroup.Keyword] = {GlotType.SEMICOLON}.union(tokenizer.keywords())

_group_set_by_grouptype[_TokTypeGroup.Other] = {
    GlotType.L_PAREN,
    GlotType.R_PAREN,
    GlotType.L_BRACKET,
    GlotType.R_BRACKET,
    GlotType.L_BRACE,
    GlotType.R_BRACE,
    GlotType.COMMA,
    GlotType.DOT,
    GlotType.DASH,
    GlotType.PLUS,
    GlotType.DCOLON,
    GlotType.DQMARK,
    GlotType.STAR,
    GlotType.BACKSLASH,
    GlotType.SLASH,
    GlotType.LT,
    GlotType.LTE,
    GlotType.GT,
    GlotType.GTE,
    GlotType.NOT,
    GlotType.EQ,
    GlotType.NEQ,
    GlotType.NULLSAFE_EQ,
    GlotType.COLON_EQ,
    GlotType.AMP,
    GlotType.DPIPE,
    GlotType.PIPE,
    GlotType.PIPE_SLASH,
    GlotType.DPIPE_SLASH,
    GlotType.CARET,
    GlotType.TILDA,
    GlotType.ARROW,
    GlotType.DARROW,
    GlotType.FARROW,
    GlotType.HASH,
    GlotType.HASH_ARROW,
    GlotType.DHASH_ARROW,
    GlotType.LR_ARROW,
    GlotType.DAT,
    GlotType.LT_AT,
    GlotType.AT_GT,
    GlotType.DOLLAR,
    GlotType.SESSION_PARAMETER,
    GlotType.DAMP,
    GlotType.DSTAR,
    GlotType.BLOCK_END,
}

# GlotType -> _TokTypeGroup
# _type_by_grouping = {g: t for t, g in _grouping_by_type.items()}
_group_type_by_glot_type: dict[GlotType, _TokTypeGroup] = {}
for groupType, groupSet in _group_set_by_grouptype.items():
    for glotType in groupSet:
        _group_type_by_glot_type[glotType] = groupType

def keywords(): return tokenizer.keywords()

def get_group_names(glotType: GlotType) -> str:
    return _group_type_by_glot_type[glotType].name.lower()
    # _grouping_by_type[]

def token_type_names() -> list[str]: 
    return [name.lower() for name, type in _TokTypeGroup.__members__.items()]

# class _data_model: # a fake replecement of the data_model module
#     def is_var(tok_text: str): return
#     def is_tree(tok_text: str): return
#     def is_table(tok_text: str): return
#     # is_schema can be constructed from sapi_sys.sapi_trees or from columns_query
#     # is_routine requires from meta data queries
#     # 

"""
Semicolon:        -
DataType:             long-list
Keyword:          long-list
String:           -
Number:           -
Variable:         var/identifier
Table:            var/identifier
Routine:          var/identifier
Schema:           var/identifier
EmbeddedVariable: colon followed by var/identifier
"""

"""
	namespace: evt. Schema, Tree, Table, View
	type:      DataType
	variable:  Variable, evt. Schema, Tree, Table, View, evt. all non-routine identifiers
	function:  Routine
	keyword:   Keyword, Semicolon
	modifier:  evt. secondary keywords, evt. hijack for View, Tree
	comment:   spacing between tokens, unless error. alternatively, get comments glotToken or recalculate
	string:    String
	number:    Number
	operator:  Others
    regexp:    evt. hijack for something
"""